name: Execução Perfecto - sample

on:
  workflow_dispatch:
    
jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        android: [ 9 ]
        state: [ 'Online' ]
      
      max-parallel: 1

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install expect tree
        pip3 install -r requirements.txt
      
    - name: Upload APK
      run: |
        python3 scripts/upload_apk.py ${{ secrets.PERFECTO_CLOUD_NAME }} ${{ secrets.PERFECTO_SECRET_TOKEN }} resources/app/sample_apk_debug.apk contador_sample.apk

    - name: Run Tests
      run: |
        robot -d results -i poc -v SESSION_TYPE:perfecto -v PERFECTO_CLOUD_NAME:${{ secrets.PERFECTO_CLOUD_NAME }} -v PERFECTO_SECRET_TOKEN:${{ secrets.PERFECTO_SECRET_TOKEN }} tests

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: resultados
        path: results/