name: Testes de integração

on:
  workflow_dispatch:

jobs:
  testes:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: pip3 install -r requirements.txt

    - name: Start AppiumServer
      run: |
        chmod +x ./scripts/startAppiumServer.sh
        ./scripts/startAppiumServer.sh
      shell: bash

    - name: Start Emulator
      run: |
        emulator -avd Pixel_3a_API_33_x86_64 &
        chmod +x ./scripts/wait_device.sh
        ./scripts/wait_device.sh  240
      shell: bash

    - name: Run Tests
      continue-on-error: true
      run: |
        robot -d results .
      shell: bash

    - name: Kill Emulator
      run: |
        adb -s emulator-5554 emu kill
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: resultados-testes
        path: results/
