name: Testes de integração

on:
  push:
    branches: [ main ]

jobs:
  testes:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: pip3 install -r requirements.txt

    - name: Start AppiumServer
      run: |
        chmod +x ./scripts/startAppiumServer.sh
        ./scripts/startAppiumServer.sh
      shell: bash

    - name: Create AVD
      continue-on-error: true
      uses: reactivecircus/android-emulator-runner@v2.27.0
      with:
        api-level: 30
        target: default
        arch: arm64-v8a
        profile: Nexus 6
        script: python3 -m robot -d results .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: resultados-testes
        path: results/
